- hosts: server1
  become: true
  remote_user: ubuntu
  tasks:
  - name: Download jboss 7.4 {{ dwnld }}
    ansible.builtin.get_url:
      url: http://158.220.102.185/jboss/jboss-eap-7.3.zip
      dest: /home/ubuntu/jboss-eap-7.3.zip
  - name: Unzip jboss-eap-7.3.zip
    ansible.builtin.unarchive:
      src: /home/ubuntu/jboss-eap-7.3.zip
      dest: /home/ubuntu/
      remote_src: yes
  - name: Deploy on jboss
    ansible.builtin.get_url:
      url: '{{ dwnld }}'
      dest: /home/ubuntu/jboss-eap-7.3/standalone/deployments/
  - name: Start Jboss
    ansible.builtin.shell: nohup sh /home/ubuntu/jboss-eap-7.3/bin/standalone.sh -b 0.0.0.0 &
