- hosts: server1
  become: true
  remote_user: ubuntu
  tasks:
  - name: Install java 8
    apt:
      name: openjdk-8-jdk
      state: latest
  - name: Install unzip
    apt:
      name: unzip
      state: lates
  - name: Download jboss 7.4 {{ dwnld }}
    ansible.builtin.get_url:
      url: https://software-installers-dc.s3.us-west-2.amazonaws.com/jboss-eap-7.4.0.zip
      dest: /home/ubuntu/jboss-eap-7.4.0.zip
  - name: Unzip jboss-eap-7.4.0.zip
    ansible.builtin.unarchive:
      src: /home/ubuntu/jboss-eap-7.4.0.zip
      dest: /home/ubuntu/
      remote_src: yes
  - name: Create user
    command: /home/ubuntu/jboss-eap-7.4/bin/add-user.sh -u 'admin' -p 'admin'
  - name: Deploy on jboss
    ansible.builtin.get_url:
      url: '{{ dwnld }}'
      dest: /home/ubuntu/jboss-eap-7.4/standalone/deployments/
  - name: Start Jboss
    command: sh /home/ubuntu/jboss-eap-7.4/bin/standalone.sh -b 0.0.0.0 &
